### ISSUE TITLE
Non IFiles not supported yet

### ISSUE THREAD

**Issue by IgnacioHR** [vladdu/lsp4e#1]
I've just uploaded an image that shall be self explanatory.

I'm not 100% sure this is the place to report this bugs

![workspace_-_eclipse](https://user-images.githubusercontent.com/16385090/28456956-78a8926e-6e04-11e7-83c7-29ee366cf5fb.jpg)

**Comment by vladdu** [comment]
Hi! 
I am only forking the code here to be able to work easier on it, for my own use. 

Please report problems at https://bugs.eclipse.org/bugs/buglist.cgi?component=General&product=lsp4e (there is a "New" link there)

**Comment by IgnacioHR** [comment]
Thanks!
